### ISSUE TITLE
Status Devs Meeting 17 Agenda

### ISSUE THREAD

**Issue by mandrigin** [status-im/pm#30]
Meeting Date/Time: Monday 2019-05-07 at 13:00 UTC
Meeting Duration 1.5 hours
YouTube Live Stream Link https://www.youtube.com/c/Statusim/live
Livepeer Live Stream Link TBD

For each agenda item, please provide context (things non-initiated people need to know, links etc) and goal (desired outcome of discussion) for agenda items.

Please comment below with things you want to discuss, together with context and desired outcome.

**Comment by oskarth** [comment]
@mandrigin are we going ahead with this one for 100%? Just want to confirm

**Comment by mandrigin** [comment]
@oskarth I asked @corpetty to help with leading it, but it will probably be very empty... still might be some topics to discuss.

**Comment by oskarth** [comment]
Would it make sense to skip this Core dev call? Nothing on agenda and seems like a lot of people are out.

**Comment by oskarth** [comment]
We skipped this. Date updated.

**Comment by oskarth** [comment]
Missing notes, transcript and next issue.

**Comment by mandrigin** [comment]
next meeting: https://github.com/status-im/pm/issues/34

**Comment by mandrigin** [comment]
Transcript bounty: https://github.com/status-im/pm/issues/35
