### ISSUE TITLE
Status Dev Meeting 18 Agenda

### ISSUE THREAD

**Issue by mandrigin** [status-im/pm#34]
Meeting Date/Time: Monday 2019-05-20 at 13:00 UTC
Meeting Duration 1.5 hours
YouTube Live Stream Link https://www.youtube.com/c/Statusim/live
Livepeer Live Stream Link TBD

For each agenda item, please provide context (things non-initiated people need to know, links etc) and goal (desired outcome of discussion) for agenda items.

Please comment below with things you want to discuss, together with context and desired outcome.

**Comment by mandrigin** [comment]
@cammellos, I guess it would be nice to discuss the protocol negotiation on this meeting? (cc @oskarth)

**Comment by cammellos** [comment]
@mandrigin yes, I think people should maybe read ahead https://discuss.status.im/t/topic-negotiation-and-device-to-device-communication-proposal/1216 so we can make an informed decision

**Comment by corpetty** [comment]
I would like to discuss the PR process and how we give better context to what needs to be done.  For instance, during the recent security issue with desktop, a PR was merged but testing didn't quite know that new binaries needed to be cut before testing. 

In essence, how can we me the requirements of a finished PR more clear, as well as the baton that needs to be passed for each of those along various stages?

**Comment by mandrigin** [comment]
Notes: https://notes.status.im/core-dev-call-18-agenda

**Comment by mandrigin** [comment]
Next agenda: https://github.com/status-im/pm/issues/38
Transcript bounty: https://github.com/status-im/pm/issues/37
