### ISSUE TITLE
Status Dev Call 20 Agenda

### ISSUE THREAD

**Issue by mandrigin** [status-im/pm#40]
Meeting Date/Time: Monday 2019-06-17 at 13:00 UTC
Meeting Duration 1.5 hours
YouTube Live Stream Link https://www.youtube.com/c/Statusim/live
Livepeer Live Stream Link TBD

For each agenda item, please provide context (things non-initiated people need to know, links etc) and goal (desired outcome of discussion) for agenda items.

Please comment below with things you want to discuss, together with context and desired outcome.

**Comment by gravityblast** [comment]
I would like to talk about the changes in status-go and the new APIs exposed to status-react to allow multi-account.

Issue: [multi-account support from main HD Wallet](https://github.com/status-im/status-go/issues/1479)

**Comment by rachelhamlin** [comment]
Perhaps we can talk about multi-account in this order:

- Summary of recent multi-account work and what's changing (@guylouis)
- Status-go APIs exposed to status-react (@gravityblast) 
- Migrating users to multi-account (@flexsurfer + me)

[Multi-account weekly notes](https://notes.status.im/rZXAblf8TNGSIszK-fbtqQ?view), [migration strategy notes](https://notes.status.im/u2xz0gFXSvmf6Xyat-eLfw?view)

**Comment by corpetty** [comment]
I would also like to discuss how we differentiate between things that won't change for a while and things that will after V1.  

I understand that go modules are somewhat of an endeavor, but I want to make sure we don't change something we spend a bunch of money auditing for V1.

**Comment by oskarth** [comment]
Closing as outdated.
