### ISSUE TITLE
Status Dev Call 21 Agenda 

### ISSUE THREAD

**Issue by guylouis** [status-im/pm#42]
Meeting Date/Time: Monday 2019-07-01 at 13:00 UTC
Meeting Duration 1.5 hours
YouTube Live Stream Link https://www.youtube.com/c/Statusim/live
Livepeer Live Stream Link TBD

For each agenda item, please provide context (things non-initiated people need to know, links etc) and goal (desired outcome of discussion) for agenda items.

Please comment below with things you want to discuss, together with context and desired outcome.

**Comment by guylouis** [comment]
Apart from the swarm updates, I think we could discuss 

- **impact of multi-account on sending transactions from chat** 
we outlined in a call last week that we'd need to set-up a ownership mechanism for A to prove ownership of the account he's using to send funds in chat to B
notes of the discussion: https://notes.status.im/9O5GHmMaRZS9LD1GLH-5yA

- **backward compatibility (from beta to v1)**
We have discussed in the past weeks how we manage our migration from beta to v1 focusing on how we tackle the use of a new whisper path that is now different from the wallet path. The goal being to allow v1 users to still use (if they want to) their old whisper ID. 
There's actually more to consider about protocol and our dB structure if we maintain this backward compatibility
Been discussed last week on #status-multiaccount channel, with following analysis from Eric
https://hackmd.io/FA4s2ubYSWaB5x-wx8SSAg

**Comment by hesterbruikman** [comment]
Notes of the call here: https://notes.status.im/IF952S7cQ5m7EpZCP-yZew?view

**Comment by oskarth** [comment]
Closing as outdated.
