### ISSUE TITLE
Status Dev Call 22 Agenda

### ISSUE THREAD

**Issue by oskarth** [status-im/pm#43]
Meeting Date/Time: Monday 2019-07-29 at 13:00 UTC (moved)
Meeting Duration 1.5 hours
YouTube Live Stream Link https://www.youtube.com/c/Statusim/live
Livepeer Live Stream Link TBD

For each agenda item, please provide context (things non-initiated people need to know, links etc) and goal (desired outcome of discussion) for agenda items.

Please comment below with things you want to discuss, together with context and desired outcome.

**Comment by oskarth** [comment]
swarm updates:
- SNT utility: sticker; tribute; dapp store; teller; network incentive; token-economics;
- core-improvement; protocol; dao; Core UI; keycard/multiaccount; qa/janitor; embark;nimbus

**Comment by oskarth** [comment]
We were 17 people in the Core+Core UI standup, and no one had anything for Core Dev call (and nothing for agenda), so we are going to go ahead and cancel it and let people focus on shipping v1.

Core standup notes are here: https://notes.status.im/RmkSvlofR0G8RuSzbobWtg

V1 scope cutting call: https://notes.status.im/v1-cut-scope#4-OUTCOME-OF-CALL-Decisionaction-points

**Comment by rajanie** [comment]
We can re-use this agenda

**Comment by yenda** [comment]
- do we need to hire a tech lead, what is he going to do, why can't we do it? https://status.im/contribute/open_positions.html?gh_jid=1792602
- upgrade react-native:
    - move form deprecated internal libraries to the community one, for the 64 bits build testing, no need to get the webview working yet
    - upgrade react-native to 0.60
    - use hermes js engine on Android
- move from realm to status-go discussion: login changes

**Comment by oskarth** [comment]
https://notes.status.im/wTzxVs4wTeehqsptOWIkNg

**Comment by oskarth** [comment]
https://notes.status.im/wTzxVs4wTeehqsptOWIkNg#

**Comment by oskarth** [comment]
Closing as outdated.
