### ISSUE TITLE
Status Dev Call 23 Agenda

### ISSUE THREAD

**Issue by rajanie** [status-im/pm#45]
Testing new monthly format

Meeting Date/Time: Monday August 26, 2019 @14:00
Meeting Duration 1.5 hours
YouTube Live Stream Link https://www.youtube.com/c/Statusim/live

Swarm Updates: 
- Core @rachelhamlin 
- Design @hesterbruikman 
- Protocol @oskarth 
- Keycard @guylouis 
- Embark/Teller @iurimatias 
- Security/Infra @corpetty @jakubgs 
- QA @annadanchenko 

Additional Agenda topics: Please comment below

**Comment by guylouis** [comment]
I will be ooo on 26/08. Here's Keycard swarm update
- keycard integration is ok for code freeze. Kudos to Dmitryn.
- keycard integration back log is [here](https://notes.status.im/iN1QNRYTRtWDHG6l5rVgrQ?both) and mostly consist of improvement/debugging to reach for v1 release, and features (iOS integration, Ledger Nano X integration) that were pushed out of v1
- research effort ongoing about using Keycard in trustless payment network. Posts to come on discuss very soon
- we're also preparing devcon 5 Keycard workshop

**Comment by rajanie** [comment]
Engagement survey

**Comment by hesterbruikman** [comment]
- @andmironov is back from Greece, @errorists is burning (OOO) till Sept 4th, Simon and Hester just got back from (Eth)Berlin. Hester OOO Wed Aug 28th -  Istanbul
- Ongoing support for PR's. Please tag @errorists or @andmironov, apologies for any delays during our vacation breaks.
- Revamp of Teller designs and branding materials by Simon, updates already implemented by @richard-ramos and Jonathan R. Check out the [Teller DApp](https://status-im.github.io/status-teller-network/build) on Rinkeby in Status Browser. Work on more structural design changes in Simon's kitchen.
- UX testing of Teller at EthBerlin. Kudos to @richard-ramos for helping us set up! Summary to follow. Ping Hester if you want access to recordings. Findings emphasize the importance of DApp integration with transaction/contract signing and Chat key/Wallet address permissions. Suggest a stronger collaboration between Teller and Core to get these flows right.
- Onboarding illustrations are coming! Objective is to make the Core app inviting for newcomers and more importantly nudge to help people understand some key concepts such as key-based identity, browser and chat. Awesome work by @errorists in directing agency Tubik on this.
- Presentation on [Helping people understand web3](https://notes.status.im/p/HJEx3sTXH#/) / a.k.a designing to build a new mental model
- In recruitment process with @jonathanbarker and @rachelhamlin to hire a tem UI engineer for our list of identified '[UI fixes](https://docs.google.com/spreadsheets/d/1OD-dtE6moWVkWYg5ALFDkcfMsINuxi0zs9_5kd2cSp4/edit#gid=0)'
- We have a [long wishlist of design projects](https://www.wrike.com/workspace.htm?acc=2688416#path=reports-new&reportId=35434788) to get to, including improvements to QR codes and 'friends onboarding', in-app notifications, Chat reactions, status sharing, etc. We'll expand on and prioritize this list during our team meeting Sept 19 in Istanbul.

**Comment by yenda** [comment]
I'm ooo but here is my short update: realm is very close to be completely removed, only non security critical data is still stored, 4 small services are required to replace them, probably finished by end of week and integrated next week. Now focused on fixing bugs and critical issues for end of September freeze

**Comment by rajanie** [comment]
Here are the notes https://notes.status.im/llyn1yP-SVuBB40j4aJqFw#
