### ISSUE TITLE
Core dev call #34

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/pm#59]
Monday August 24
14:00 UTC
Participate: [meet.google.com/uyn-yfrq-uka](meet.google.com/uyn-yfrq-uka)
View: [https://www.youtube.com/channel/UCFzdJTUdzqyX4e9dOW7UpPQ/videos](https://www.youtube.com/channel/UCFzdJTUdzqyX4e9dOW7UpPQ/videos)

0. Assign notetaker
1. Agenda setting (~5')
2. Announcements (~5')
    a. ...
3. Review [previous actions](https://notes.status.im/core-dev-call_33#) (~5') _Don't believe there were any captured_
4. Specs review > open PR's for Discussion (~10')
a. [#146](https://github.com/status-im/specs/pull/146) Add grant, separate devices and ephemeral keys usage
b. [[#145]](https://github.com/status-im/specs/pull/145) Added EmojiReaction payload types
5. Expected changes/proposals 
a. Mentions
b. Profile pics
c. Chat in apps
6. AOB (~5')

YouTube: https://www.youtube.com/watch?v=U6u8Ee1inps
Google Hangouts: https://meet.google.com/uyn-yfrq-uka
Notes: https://notes.status.im/core-dev-call_34#

**Comment by rasom** [comment]
Mentions in desktop version
