### ISSUE TITLE
Status Devs Meeting 8

### ISSUE THREAD

**Issue by oskarth** [status-im/pm#8]
Status Devs Meeting 8, Agenda
Meeting Date/Time: Monday 2018-12-03 at 12:00 UTC
Meeting Duration 1.5 hours
YouTube Live Stream Link https://www.youtube.com/c/Statusim/live
Livepeer Live Stream Link TBD

Notes/Agenda: https://notes.status.im/vV9787u1RvSuop3x3jPXfw

Please provide context (things non-initiated people need to know, links etc) and goal (desired outcome of discussion) for agenda items.

**Comment by oskarth** [comment]
Please add stuff before end of day Wednesday to allow proper preparation by participants. Please also include context and specific goals so everyone can read up beforehand, and know what is expected. (This has been repeated feedback)

**Comment by mandrigin** [comment]
> What are we going to do about it?
https://github.com/status-im/status-react/issues/6906
https://github.com/status-im/status-react/pull/6915
https://github.com/status-im/status-react/pull/6918

**Comment by gravityblast** [comment]
Sorry if I haven't added this earlier but I would like to take about:

1 - Decoupling whisper and wallet keys: [https://discuss.status.im/t/multiple-whisper-and-wallet-keys/817](https://discuss.status.im/t/multiple-whisper-and-wallet-keys/817)

2 - Steps needed + ideas/help needed on how to exchange wallet address for in-chat transactions [https://notes.status.im/xIn9qA-3SWCbp7jkJCJjOg](https://notes.status.im/xIn9qA-3SWCbp7jkJCJjOg)

2 - Our "Non-wallet usage of keys derived from BIP-32 trees" proposal has been accepted (still in Draft). Kudos @bitgamma - [https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1581.md](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1581.md)

**Comment by oskarth** [comment]
@gravityblast Thanks - could you provide a brief summary on context and what desired outcome you want? I doubt everyone will read the full Discuss thread and understand what we want to achieve, so a tldr would be useful to maximize engagement from people.

**Comment by mandrigin** [comment]
Upgradeable **message-id**s open forum.

We had problems with message IDs for quite a while and they are impeding the upgrade, let's fix them finally.

More context: https://github.com/status-im/status-react/issues/6956

**Comment by oskarth** [comment]
Agenda https://notes.status.im/vV9787u1RvSuop3x3jPXfw?both

**Comment by oskarth** [comment]
Notes https://notes.status.im/Z9xG4bACS9WP_9hQtFbVjg

https://github.com/status-im/pm/issues/9
